ClinicWEB/Controllers/AppointmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClinicWEB.Models;

namespace ClinicWEB.Controllers
{
    public class AppointmentController : Controller
    {
        private readonly ClinicContext _context;

        public AppointmentController(ClinicContext context)
        {
            _context = context;
        }

        // GET: Appointment
        public async Task<IActionResult> Index()
        {
            var clinicContext = _context.Appointments.Include(a => a.Doctor).Include(a => a.Patient);
            return View(await clinicContext.ToListAsync());
        }

       

        // GET: Appointment/Create
        public IActionResult Create()
        {
            ViewData["DoctorId"] = new SelectList(_context.Doctors, "Id", "FullName");
            ViewData["PatientId"] = new SelectList(_context.Patients, "Id", "FullName");
            return View();
        }

        public JsonResult GetPatients(int id)
        {
            var tempPatients = from a in _context.Patients
                           join b in _context.Registrations
                           on a.Id equals b.PatientId
                           select new
                           {
                               Id = a.Id,
                               FullName = a.FullName,
                               DoctorId = b.DoctorId

                           };
            
            var patients = tempPatients.Where(x => x.DoctorId == id).ToList();

            return Json(new SelectList(patients, "Id", "FullName"));
        }

        public JsonResult GetDate(int PatientId, int DoctorId)
        {
            var date = _context.Registrations
                .Where(x => x.DoctorId == DoctorId)
                .Where(y => y.PatientId == PatientId)
                .Select(i => i.DateTime);
            //var date = _context.Registrations.Where(i => i.PatientId == id).FirstOrDefault();
            return Json(date);
        }

        public JsonResult GetSpecializations(int DoctorId)
        {
            var specializations = _context.Doctors.
                Where(x => x.Id == DoctorId).
                Select(y => y.Specialization);

            return Json(specializations);
        }
        // POST: Appointment/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Appointment appointment)
        {
            if (ModelState.IsValid)
            {
                var record = _context.Registrations.
                    Where(i => i.PatientId == appointment.PatientId && i.DoctorId == appointment.DoctorId).
                    FirstOrDefault();

                _context.Registrations.Remove(record);
                _context.Add(appointment);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index","Home");
            }
            ViewData["DoctorId"] = new SelectList(_context.Doctors, "Id", "Id", appointment.DoctorId);
            ViewData["PatientId"] = new SelectList(_context.Patients, "Id", "Id", appointment.PatientId);
            return View(appointment);
        }

        
        // GET: Appointment/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointments
                .Include(a => a.Doctor)
                .Include(a => a.Patient)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (appointment == null)
            {
                return NotFound();
            }

            return View(appointment);
        }

        // POST: Appointment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var appointment = await _context.Appointments.FindAsync(id);
            _context.Appointments.Remove(appointment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AppointmentExists(int id)
        {
            return _context.Appointments.Any(e => e.Id == id);
        }

        public JsonResult GetWorkload(int DoctorId)
        {
            var date1 = DateTime.Now.AddMonths(-1);
            var date2 = DateTime.Now.AddMonths(1).ToString("yyyy-MM-dd");
            var count = _context.Appointments.Where(x => x.DoctorId == DoctorId)
                .Count();
            return Json(count);
        }

        public IActionResult Epidemic()
        {
            ViewData["Epidemics"] = new SelectList(_context.Appointments, "Diagnosis", "Diagnosis");
            return View();
        }

        public JsonResult GetIllCount(string diagnosis)
        {
            var count = _context.Appointments.Where(i => i.Diagnosis == diagnosis).Count();
            return Json(count);
        }
    }
}

ClinicWEB/Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClinicWEB.Models;

namespace ClinicWEB.Controllers
{
    public class DoctorController : Controller
    {
        private readonly ClinicContext _context;

        public DoctorController(ClinicContext context)
        {
            _context = context;
        }

        // GET: Doctor
        public async Task<IActionResult> Index()
        {
            return View(await _context.Doctors.ToListAsync());
        }

        // GET: Doctor/Details/5
        

        // GET: Doctor/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Doctor/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FullName,Specialization")] Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(doctor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(doctor);
        }

        // GET: Doctor/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctor = await _context.Doctors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (doctor == null)
            {
                return NotFound();
            }

            return View(doctor);
        }

        // POST: Doctor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var doctor = await _context.Doctors.FindAsync(id);
            _context.Doctors.Remove(doctor);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DoctorExists(int id)
        {
            return _context.Doctors.Any(e => e.Id == id);
        }
    }
}

ClinicWEB/Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClinicWEB.Models;

namespace ClinicWEB.Controllers
{
    public class PatientController : Controller
    {
        private readonly ClinicContext _context;

        public PatientController(ClinicContext context)
        {
            _context = context;
        }

        // GET: Patient
        public async Task<IActionResult> Index()
        {
            return View(await _context.Patients.OrderBy(i=>i.Birthday).ToListAsync());
        }

        // GET: Patient/Create
        public IActionResult Create(bool isFailed = false)
        {
            ViewBag.IsFailed = isFailed;
            return View();
        }

        // POST: Patient/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FullName,Birthday")] Patient patient)
        {
            if (ModelState.IsValid)
            {
                var flag = _context.Patients.Any(i => i.FullName == patient.FullName && i.Birthday == patient.Birthday);
                if(flag)
                {
                    return RedirectToAction("Create", new { isFailed = true });
                }
                ViewBag.Incorrect = null;
                _context.Add(patient);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            return View(patient);
        }

        
        // GET: Patient/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patient = await _context.Patients
                .FirstOrDefaultAsync(m => m.Id == id);
            if (patient == null)
            {
                return NotFound();
            }

            return View(patient);
        }

        // POST: Patient/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var patient = await _context.Patients.FindAsync(id);
            _context.Patients.Remove(patient);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PatientExists(int id)
        {
            return _context.Patients.Any(e => e.Id == id);
        }
    }
}

ClinicWEB/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClinicWEB.Models;

namespace ClinicWEB.Controllers
{
    public class ServiceController : Controller
    {
        private readonly ClinicContext _context;

        public ServiceController(ClinicContext context)
        {
            _context = context;
        }

        // GET: Service
        public async Task<IActionResult> Index()
        {
            return View(await _context.Services.ToListAsync());
        }

        // GET: Service/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Service/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Price")] Service service)
        {
            if (ModelState.IsValid)
            {
                _context.Add(service);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(service);
        }

        

        // GET: Service/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var service = await _context.Services
                .FirstOrDefaultAsync(m => m.Id == id);
            if (service == null)
            {
                return NotFound();
            }

            return View(service);
        }

        // POST: Service/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var service = await _context.Services.FindAsync(id);
            _context.Services.Remove(service);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ServiceExists(int id)
        {
            return _context.Services.Any(e => e.Id == id);
        }
    }
}

ClinicWEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClinicWEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/My_Css.css" />
    <link href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" rel="stylesheet">
</head>
<body>
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
            <svg class="bi me-2" width="40" height="32"><use xlink:href="~/img/поликлиника.png"></use></svg>
            <i id="iconId" class="fas fa-hospital fa-3x" >Поликлиника</i>
        </a>

        <ul class="nav nav-pills">
            <li class="nav-item"><a asp-controller="Home" asp-action="Index" class="nav-link active" aria-current="page">Меню</a></li>
            <li class="nav-item"><a asp-controller="Patient" asp-action="Index" class="nav-link">Пациенты</a></li>
            <li class="nav-item"><a asp-controller="Doctor" asp-action="Index" class="nav-link">Врачи</a></li>
            <li class="nav-item"><a asp-controller="Registration" asp-action="Index" class="nav-link">Записи на приём</a></li>
            <li class="nav-item"><a asp-controller="Appointment" asp-action="Index" class="nav-link">Медкарты</a></li>
            <li class="nav-item"><a asp-controller="Sell" asp-action="Index" class="nav-link">Учёт услуг</a></li>
            <li class="nav-item"><a asp-controller="Service" asp-action="Index" class="nav-link">Услуги</a></li>

        </ul>
    </header>
    <div class="container">
        <main role="main" class="pb-3">


            @*<!--Success Dialog Start-->
            <div id="myModalSuccess" class="modal fade text-width:30%;" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h2>Алерт</h2>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
                        <div id="myModalSuccessAlertBody" class="modal modal-body alert alert-success">
                            aleeeeert booooooooody
                        </div>
                        <div class="modal-footer">
                            &nbsp;
                            <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
                        </div>

                    </div>
                </div>

            </div>
            <!--Success Dialog End-->
                *@




            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; 2021 - ClinicWEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>




    @RenderSection("Scripts", required: false)
</body>
</html>